import type { Metadata } from "next";
import { cookies } from 'next/headers';
import { setServerLanguage } from '@/lib/i18n';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeToggle } from '@/components/ui';
import ClientInit from '@/components/ClientInit';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // if a cookie-set language exists, use that for the document's lang attribute
  // Note: cookies() returns a Promise in Next.js' server runtime and must be awaited.
  const cookieStore = await cookies();
  const cookieLang = cookieStore.get('lang')?.value;
  const htmlLang = cookieLang === 'vi' ? 'vi' : 'en';
  // set the i18n singleton language during server render so server-rendered
  // content uses the preferred language
  setServerLanguage(htmlLang);

  return (
    <html lang={htmlLang}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="fixed top-4 right-4 z-50">
          <ThemeToggle />
        </div>
        <ClientInit />
        {children}
      </body>
    </html>
  );
}
